/**
 * Los textos del centro de mando del piloto automático (fase 1: las tres
 * propuestas). Viven aquí y NO en `es.json` a propósito: son propuestas para
 * que Nico elija; la que gane se muda a i18n en la fase 2 y las otras dos se
 * borran sin dejar claves huérfanas.
 *
 * Regla de vocabulario (Nico, 29-09): «piloto automático» es el modo en que los
 * agentes operan solos la inmobiliaria; el chat es otra cosa. Aquí no aparece
 * la palabra «chat».
 */

export const TEXTOS = {
  pagina: {
    titulo: 'Piloto automático · propuestas',
    bajada:
      'Tres maneras de ver el centro de mando del piloto automático. Cada una lee los mismos datos; escoge la que se sienta como tu panel de control.',
    volver: 'Volver al piloto automático',
    selector: 'Dirección de diseño',
    fuente: 'Datos que se ven',
    real: 'Real',
    muestra: 'Muestra encendida',
    direcciones: {
      A: { letra: 'A', nombre: 'Núcleo', idea: 'El piloto automático en el centro, con sus medidores alrededor.' },
      B: { letra: 'B', nombre: 'Cabina', idea: 'Una sala de operaciones: todo a la vista en una grilla densa.' },
      C: { letra: 'C', nombre: 'Misión del día', idea: 'El día como una misión: lo que corrió, lo que corre y lo que viene.' },
      E: { letra: '★', nombre: 'Elegida', idea: 'La que escogió Nico: la Cabina con el núcleo arriba y la línea del día.' },
    },
  },
  muestra: {
    distintivo: 'MUESTRA — no son datos reales',
    explicacion:
      'Datos inventados para ver el panel encendido y con trabajo. Nada de esto viene de tu inmobiliaria y nada se ejecuta.',
    noSeAbre: 'En la muestra los casos no se abren: cambia a «Real» para trabajar con los tuyos.',
    ctaNoEjecuta: 'Es la muestra: aquí no se cambia nada. En «Real» este botón cambia al agente de verdad.',
  },
  /** El popover de cada agente de la tripulación (Nico, 05-10 19:30). */
  agente: {
    queHace: 'Qué hace',
    suModo: (modo: string) => `Su modo · ${modo}`,
    loUltimo: 'Lo último',
    hoy: 'Hoy',
    accionesHoy: (n: number) => (n === 1 ? '1 acción' : `${n} acciones`),
    sinAcciones: 'Sin acciones recientes',
    cambiarModo: 'Modo del agente',
    encender: 'Activar',
    apagar: 'Desactivar',
    encendido: (nombre: string) => `${nombre} quedó activo para tu inmobiliaria.`,
    apagado: (nombre: string) => `${nombre} quedó apagado para tu inmobiliaria.`,
    modoCambiado: (nombre: string, modo: string) => `${nombre} quedó en ${modo.toLocaleLowerCase('es')}.`,
    soloAdmin: 'Sólo un administrador de tu inmobiliaria puede activarlo, apagarlo o cambiarle el modo.',
    noDisponible: 'En pausa: Leasefy todavía no lo ofrece.',
    loPrendeLeasefy: 'Apagado por ahora: lo prende Leasefy.',
    sinModo: 'Su modo todavía no se puede cambiar desde aquí.',
    abrirDetalle: (nombre: string) => `Ver a ${nombre}: qué hace, su modo y lo último`,
  },
  /** El popover del orbe del piloto automático (núcleo). */
  piloto: {
    titulo: 'Piloto automático',
    modoGeneral: 'Modo general',
    otros: (n: number) => (n === 1 ? '1 agente en otro modo' : `${n} agentes en otro modo`),
    agentes: 'Los agentes encendidos',
    ahora: 'Haciendo ahora',
    nadaAhora: 'Nada en curso en este momento.',
    director: 'El director',
    directorApagado: 'El director no está encendido para tu inmobiliaria.',
    abrirPlan: 'Abrir el plan',
    autonomia: 'Autonomía',
    abrirDetalle: 'Ver el estado del piloto automático',
  },
  estado: {
    ok: 'En línea',
    atencion: 'Atención',
    critico: 'Crítico',
    desconocido: 'Sin lectura',
    apagado: 'Apagado',
  },
  pieza: {
    cargando: 'Leyendo…',
    sinDato: 'Sin dato todavía',
    noDisponible: 'Esta lectura todavía no está disponible.',
    reintentar: 'Intentar de nuevo',
  },
  queEs: {
    pulso: 'el pulso del piloto automático',
    bandeja: 'las decisiones que esperan',
    actividad: 'lo que hicieron los agentes',
    flota: 'los agentes y su modo',
    director: 'el plan del director',
    metas: 'las metas del director',
  },
  kpi: {
    recuperado: 'Recuperado este mes',
    recuperadoNota: 'Lo que los agentes ayudaron a cobrar en el mes.',
    esperan: 'Decisiones que esperan',
    altas: 'de prioridad alta',
    alta: 'de prioridad alta',
    atrasadas: 'llevan más de una semana',
    ningunaAtrasada: 'ninguna lleva más de una semana',
    agentes: 'Agentes que actúan',
    agentesDe: (n: number) => `de ${n} encendidos`,
    plan: 'Plan del día',
    planDe: (n: number) => `de ${n} órdenes hechas`,
    metas: 'Metas del director',
    metasDe: (n: number) => (n === 1 ? 'avance de 1 meta activa' : `avance medio de ${n} metas activas`),
    llamadas: 'Llamadas hoy',
    conversaciones: 'Conversaciones abiertas',
    resueltas: 'Resueltas hoy',
    planeados: 'Contactos planeados',
    promesas: 'Acuerdos de pago hoy',
    alertas: 'Alertas',
    severidad: { critica: 'críticas', alta: 'altas', media: 'medias', info: 'informativas' },
    /** «1 crítica», «2 altas». */
    severidadN: (s: 'critica' | 'alta' | 'media' | 'info', n: number) =>
      n === 1 ? { critica: 'crítica', alta: 'alta', media: 'media', info: 'informativa' }[s] : { critica: 'críticas', alta: 'altas', media: 'medias', info: 'informativas' }[s],
    altasN: (n: number) => (n === 1 ? '1 alta' : `${n} altas`),
    atrasadasN: (n: number) => (n === 1 ? '1 lleva más de una semana' : `${n} llevan más de una semana`),
    sinAlertas: 'Sin alertas',
    actividadDias: 'Actividad por día',
    actividadDiasNota: (n: number) => `acciones registradas, últimos ${n} días completos`,
  },
  voz: {
    director: (hora: string | null) => (hora ? `El director · plan de ${hora}` : 'El director'),
    pulso: 'El pulso del piloto automático',
    apagado: 'El piloto automático está apagado',
    apagadoBajada:
      'Cuando está activo, los agentes operan solos dentro de tus topes y aquí ves en vivo qué hacen, qué viene y qué necesita de ti.',
  },
  director: {
    titulo: 'Plan del día',
    apagado: 'El director no está encendido para tu inmobiliaria',
    apagadoBajada:
      'Con el director, cada mañana el piloto automático arma el plan del día y sus metas. Mientras tanto, la voz del día es la del pulso.',
    sinPlan: 'Todavía no hay plan de hoy.',
    planeando: 'El director está armando el plan de hoy…',
    estados: {
      hechas: 'Hechas',
      enBandeja: 'Esperan tu clic',
      agente: 'Las hace el agente',
      fuera: 'Descartadas o fallidas',
    },
    metasTitulo: 'Metas',
    sinMetas: 'El director todavía no propone metas.',
    estimada: 'estimada',
    objetivo: 'objetivo',
    actual: 'hoy',
    base: 'base',
  },
  tripulacion: {
    titulo: 'La tripulación',
    bajada: 'Cada agente, su modo y lo último que hizo.',
    actua: 'Actúa con su modo',
    corre: 'Corre, todavía no actúa solo',
    apagado: 'Apagado',
    sinActividad: 'Sin acciones recientes',
    modos: { sombra: 'Manual', copiloto: 'Copiloto', autonomo: 'Automático', mixto: 'Mixto' },
  },
  enVivo: {
    titulo: 'En vivo',
    telemetria: 'Telemetría',
    ahora: 'Ahora',
    vacio: 'Nada en curso. Lo próximo que hagan los agentes entra aquí.',
    sinActividad: 'Todavía no hay acciones registradas.',
    tuEquipo: 'Tu equipo',
    anuncio: (titulo: string) => `Nuevo en vivo: ${titulo}`,
  },
  bandeja: {
    titulo: 'Te necesitan',
    urgente: 'Lo urgente',
    vacio: 'Nada espera tu decisión.',
    abrirTodo: 'Abrir la Bandeja',
    revisar: 'Revisar',
    espera: (cuanto: string) => `espera ${cuanto}`,
  },
  solos: {
    titulo: 'Hicieron solos hoy',
    porAgente: 'Por agente',
    acciones: (n: number) => (n === 1 ? '1 acción' : `${n} acciones`),
    vacio: 'Hoy todavía no hicieron nada solos.',
    recortado: 'contado sobre las últimas 50 acciones',
  },
  mision: {
    titulo: 'Misión del día',
    objetivo: 'Objetivo',
    objetivoSinDirector: 'Dejar la Bandeja en cero',
    objetivoSinDirectorNota: 'Sin plan del director, el objetivo del día es despejar lo que espera tu decisión.',
    avanceBandeja: (resueltas: number, quedan: number) => `${resueltas} resueltas · quedan ${quedan}`,
    linea: 'Hoy, hora por hora',
    corrio: 'Corrió',
    corre: 'Corre',
    viene: 'Viene',
    sinHora: 'Hoy, sin hora fija',
    loQueViene: 'Lo que viene',
    nadaViene: 'Nada programado para lo que queda del día.',
    ahora: 'Ahora',
  },
  activar: {
    invitacion: 'Enciende el piloto automático',
  },
  cajones: {
    bandeja: { titulo: 'La Bandeja', bajada: 'Todo lo que espera tu decisión, con sus filtros y sus acciones.' },
    actividad: { titulo: 'La actividad', bajada: 'Lo que hicieron los agentes y tu equipo, día por día.' },
    director: { titulo: 'El director', bajada: 'El plan de hoy, las metas y la semana, con sus acciones.' },
  },
  /** MANDO-DATOS (05-10-2026): las tendencias con datos del micro y del back. */
  tendencias: {
    recuperado30: 'Últimos 30 días',
    recuperadoSerie: (n: number) => `Lo recuperado día por día en los últimos ${n} días`,
    negocio: 'El negocio este mes',
    queEs: 'las cifras del negocio',
    recaudo: 'Recaudo del mes',
    recaudoDe: (entro: string, base: string) => `${entro} de ${base}`,
    recaudoBase: { CAUSADO: 'causados', EMITIDO: 'emitidos' },
    recaudoSinDato: 'Sin cuotas este mes para medirlo.',
    mora: 'Mora de más de 30 días',
    moraNota: (dias: string) => `equivale a ${dias} de facturación`,
    moraSube: (cuanto: string, n: number) => `subió ${cuanto} en ${n} días`,
    moraBaja: (cuanto: string, n: number) => `bajó ${cuanto} en ${n} días`,
    moraIgual: (n: number) => `igual que hace ${n} días`,
    moraSinSerie: 'Todavía no hay días suficientes para ver la tendencia.',
    horas: 'Horas ahorradas',
    horasVentana: 'en 30 días',
    estimada: 'estimada',
    medidas: (h: string) => `${h} medidas en llamadas`,
    estimadas: (h: string) => `${h} estimadas`,
    supuesto: 'Cómo se cuenta',
    horasSinEstimar: 'La parte estimada no llegó; sólo se ven las llamadas.',
    ritmo: 'El ritmo de los agentes',
    ritmoBajada: 'Lo que hicieron solos, día por día (14 días)',
    ritmoConPersona: (n: number) => (n === 1 ? '1 la decidió tu equipo' : `${n} las decidió tu equipo`),
    ritmoHoy: 'hoy va a medias',
    ritmoRecortada: 'Los días más viejos pueden quedarse cortos (más de 2.000 acciones por fuente).',
    ritmoVacio: 'Todavía no hay acciones en estos 14 días.',
    ritmoDia: (dia: string, n: number) => `${dia}: ${n} ${n === 1 ? 'acción' : 'acciones'} solas`,
    metasAparte: (n: number) => (n === 1 ? '1 estimada aparte' : `${n} estimadas aparte`),
    metasEnSuPunto: (n: number) => (n === 1 ? '1 meta activa, en su punto de partida' : `${n} metas activas, en su punto de partida`),
  },
  reloj: 'Hora de Colombia',
} as const

export type Direccion = 'A' | 'B' | 'C' | 'E'
export type Fuente = 'real' | 'muestra'
