/**
 * Contract types and interfaces
 * Types for rental contracts, signatures, and signing flow
 */

// ============================================================================
// Contract Type Enums
// ============================================================================

/**
 * Types of rental contracts
 */
export type ContractType = 'basico' | 'amoblado' | 'compartido' | 'custom';

/**
 * Contract status throughout the signing flow
 */
export type ContractStatus =
  | 'draft'                            // Borrador - being configured
  | 'pending_landlord'                 // Pendiente firma arrendador
  | 'pending_tenant'                   // Pendiente firma arrendatario
  | 'rejected_pending_modifications'   // Inquilino pidió cambios; landlord debe editar + re-firmar
  | 'signed'                           // Ambos firmaron, pendiente activar
  | 'active'                           // Activo - both signed
  | 'expired'                          // Expirado - past end date
  | 'cancelled';                       // Cancelado - terminated early

/**
 * Tipo de rechazo cuando un tenant rechaza un contrato en PENDING_TENANT_SIGNATURE.
 * - DEFINITIVE: cierra el proceso, contrato → CANCELLED, application → CONTRACT_FAILED.
 * - MODIFICATIONS: pide cambios, contrato → REJECTED_PENDING_MODIFICATIONS, landlord debe editar.
 */
export type RejectionType = 'DEFINITIVE' | 'MODIFICATIONS';

/**
 * Registro histórico de un rechazo. Una misma ronda de negociación puede tener varios.
 */
export interface ContractRejection {
  id: string;
  contractId: string;
  rejectedByUserId: string;
  type: RejectionType;
  reason: string;
  createdAt: string;
  rejectedBy: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
}

/**
 * Signature status for each party
 */
export type SignatureStatus = 'pending' | 'signed';

// ============================================================================
// Spanish Labels
// ============================================================================

/**
 * Spanish labels for contract types
 */
export const CONTRACT_TYPE_LABELS: Record<ContractType, string> = {
  basico: 'Contrato Basico',
  amoblado: 'Contrato Amoblado',
  compartido: 'Contrato Compartido',
  custom: 'Contrato Propio',
};

/**
 * Label legible para el "tipo de contrato" del lado del usuario. Como el backend no modela
 * `type` en el contract, derivamos el label del `contractOrigin`.
 */
export function getContractTypeLabel(
  contract: Pick<Contract, 'contractOrigin'>,
  locale: 'es' | 'en' = 'es',
): string {
  if (contract.contractOrigin === 'UPLOADED_PDF') {
    return locale === 'es'
      ? 'Contrato subido por el propietario'
      : 'Contract uploaded by landlord';
  }
  if (contract.contractOrigin === 'GENERATED') {
    return locale === 'es'
      ? 'Contrato generado por la plataforma'
      : 'Contract generated by the platform';
  }
  return locale === 'es' ? 'Contrato de arrendamiento' : 'Rental contract';
}

/**
 * Spanish descriptions for contract types
 */
export const CONTRACT_TYPE_DESCRIPTIONS: Record<ContractType, string> = {
  basico: 'Arriendo estandar sin muebles. Ideal para inquilinos que tienen sus propios muebles.',
  amoblado: 'Arriendo con muebles incluidos. Incluye inventario detallado de bienes.',
  compartido: 'Arriendo de habitacion con areas comunes compartidas.',
  custom: 'Sube tu propio contrato en formato PDF. Se usara como base para el proceso de firma.',
};

/**
 * Spanish labels for contract status
 */
export const CONTRACT_STATUS_LABELS: Record<ContractStatus, string> = {
  draft: 'Borrador',
  pending_landlord: 'Pendiente firma arrendador',
  pending_tenant: 'Pendiente firma arrendatario',
  rejected_pending_modifications: 'Modificaciones solicitadas',
  signed: 'Firmado — pendiente activar',
  active: 'Activo',
  expired: 'Expirado',
  cancelled: 'Cancelado',
};

/**
 * Status badge colors for contract status
 */
export const CONTRACT_STATUS_COLORS: Record<ContractStatus, string> = {
  draft: 'bg-muted text-foreground',
  pending_landlord: 'bg-plan-status-yellow-bg text-plan-status-yellow',
  pending_tenant: 'bg-plan-status-blue-bg text-plan-status-blue',
  rejected_pending_modifications: 'bg-[#F8F0E0] text-[#B7791F] dark:bg-[#B7791F]/15 dark:text-[#D2992F]',
  signed: 'bg-plan-status-blue-bg text-plan-status-blue',
  active: 'bg-plan-status-green-bg text-plan-status-green',
  expired: 'bg-muted text-muted-foreground',
  cancelled: 'bg-plan-status-red-bg text-plan-status-red',
};

// ============================================================================
// Contract Clause
// ============================================================================

/**
 * Individual clause within a contract template
 */
export interface ContractClause {
  id: string;
  title: string;
  content: string;
  required: boolean;
}

// ============================================================================
// Contract Template
// ============================================================================

/**
 * Reusable contract template with clauses
 */
export interface ContractTemplate {
  id: string;
  type: ContractType;
  name: string;
  description: string;
  clauses: ContractClause[];
}

// ============================================================================
// Signature
// ============================================================================

/**
 * Electronic signature with legal compliance metadata
 */
export interface Signature {
  signedAt: string;      // ISO date string
  signedBy: string;      // Name of signer
  signerId: string;      // User ID
  ipAddress: string;     // IP for legal record
  userAgent: string;     // Browser info for legal record
  status: SignatureStatus;
  otpVerified: boolean;       // Whether OTP verification was completed
  otpVerifiedAt?: string;     // ISO date string when OTP was verified
}

// ============================================================================
// Audit Trail
// ============================================================================

/**
 * Types of audit events in contract lifecycle
 */
export type ContractAuditEventType =
  | 'created'
  | 'sent_to_landlord'
  | 'landlord_signed'
  | 'sent_to_tenant'
  | 'tenant_signed'
  | 'activated';

/**
 * Audit event metadata
 */
export interface ContractAuditEventMetadata {
  userId?: string;
  userName?: string;
  ipAddress?: string;
  userAgent?: string;
  otpVerified?: boolean;
}

/**
 * Individual audit event in contract history
 */
export interface ContractAuditEvent {
  id: string;
  contractId: string;
  type: ContractAuditEventType;
  timestamp: string;        // ISO date string
  metadata: ContractAuditEventMetadata;
}

// ============================================================================
// Perfil tributario
// ============================================================================

/**
 * Si una parte es agente retenedor, y de qué.
 *
 * La retención en la fuente la practica **quien paga**: entre dos personas
 * naturales no hay; si el que paga es una empresa, sí. No depende de quién
 * recibe.
 */
export interface PerfilTributario {
  tipoPersona: 'NATURAL' | 'JURIDICA';
  /** Cobra IVA en sus facturas. */
  responsableIva: boolean;
  agenteRetenedorRenta: boolean;
  agenteRetenedorIva: boolean;
  agenteRetenedorIca: boolean;
  /**
   * Si algún campo se dedujo del tipo de persona en vez de leerse. Se muestra
   * en pantalla: un número calculado sobre un supuesto no se puede defender.
   */
  esPorDefecto: boolean;
}

/**
 * El régimen tributario del contrato, ya resuelto por el back con el origen
 * de cada valor. Se muestra tal cual: si la pantalla lo recalculara, sería
 * una segunda cuenta que un día no coincide con la que cobra.
 *
 * Se declara acá y no se importa de `contracts.types` por la misma razón que
 * `PerfilesDelContrato`: ese archivo es la forma del cable, éste la del
 * dominio.
 */
export type OrigenDelValorTributario =
  | 'CONTRATO'
  | 'PROPIETARIO'
  | 'TIPO_DE_INMUEBLE'
  | 'SIN_DEFINIR';

export interface ValorTributarioResuelto {
  valor: boolean | null;
  origen: OrigenDelValorTributario;
}

export interface RegimenTributarioDelContrato {
  usoComercial: ValorTributarioResuelto;
  arrendadorResponsableIva: ValorTributarioResuelto;
  inquilinoRetenedorRenta: ValorTributarioResuelto;
  inquilinoRetenedorIva: ValorTributarioResuelto;
  inquilinoRetenedorIca: ValorTributarioResuelto;
}

export interface PerfilesDelContrato {
  inquilino: PerfilTributario;
  propietario: PerfilTributario;
  inmobiliaria: PerfilTributario;
}

/**
 * Un dueño del inmueble, con su porcentaje y su parte del canon.
 *
 * 🔴 Nico, 2026-09-12: «Hay contratos que tienen tres propietarios y cada uno
 * define cuál es el porcentaje de cada uno. Hay que dividir el canon entre los
 * porcentajes que pidieron y tener la información de los tres propietarios.»
 *
 * El reparto lo hace el BACK con la misma función que la dispersión: si esta
 * pantalla lo dividiera por su cuenta, el día que las dos cuentas difieran la
 * ficha diría una cosa y el giro giraría otra.
 *
 * Los cuatro booleanos tributarios vienen CRUDOS (`null` = nadie lo afirmó),
 * no mezclados con el default de su tipo de persona: la ficha muestra sólo lo
 * que la persona TIENE, y para eso hay que distinguir «dijo que no» de «no
 * dijo».
 */
export interface PropietarioDelContrato {
  id: string;
  name: string;
  documentNumber: string;
  documentType: string | null;
  participacionBps: number;
  /** Ya escrito: `60 %`, `33,33 %`. */
  participacion: string;
  /** `null` = no hay canon, o las participaciones no suman 100 %. */
  canonCop: number | null;
  esPrincipal: boolean;
  responsableIva: boolean | null;
  agenteRetenedorRenta: boolean | null;
  agenteRetenedorIva: boolean | null;
  agenteRetenedorIca: boolean | null;
}

export interface PropietariosDelContrato {
  propietarios: PropietarioDelContrato[];
  sumaBps: number;
  /** `false` = hay que corregir el mandato; la ficha lo dice en voz alta. */
  sumanCien: boolean;
}

/**
 * Un inquilino del contrato. El principal es el titular (`Contract.tenantId`
 * y su snapshot); los demás son coarrendatarios de `contrato_inquilinos`.
 *
 * Nico, 2026-09-12: «No se presentan tanto múltiples inquilinos, pero puede
 * darse el caso: construirlo también para múltiples inquilinos.»
 */
export interface InquilinoDelContrato {
  /** `null` en el principal: no tiene fila propia, vive en el contrato. */
  id: string | null;
  userId: string | null;
  nombre: string;
  documento: string;
  email: string | null;
  telefono: string | null;
  esPrincipal: boolean;
}

/**
 * El escenario tributario del contrato: cómo se LLAMA la situación que forman
 * las dos partes, y qué genera.
 *
 * Nico, 2026-09-12: «Los contratos no están mostrando la información sobre el
 * escenario que se da en ese contrato. Ejemplo: si el inquilino es persona
 * natural y si el propietario es persona natural, el escenario de ese contrato
 * sería contrato de arrendamiento entre personas naturales. Entonces ese no va
 * a generar impuestos.»
 *
 * Los nueve códigos salen del catálogo que la inmobiliaria ya usaba en Nuby.
 * Lo calcula el back con el mismo régimen que usa el motor de cobros: la
 * pantalla lo muestra, no lo recalcula — una segunda cuenta es una cuenta que
 * un día no coincide con la que cobra.
 */
export type CodigoDeEscenario =
  | 'E1'
  | 'E2'
  | 'E3'
  | 'E4'
  | 'E5'
  | 'E6'
  | 'E7'
  | 'E8'
  | 'E9'
  | 'SIN_DEFINIR';

export interface ImpuestoDelEscenario {
  tipo: 'IVA' | 'RETEFUENTE' | 'RETEIVA';
  base: 'CANON' | 'COMISION';
  nombre: string;
  porcentaje: number;
  loPractica: 'PROPIETARIO' | 'INQUILINO';
  aCargoDe: 'INQUILINO' | 'PROPIETARIO' | 'INMOBILIARIA';
  explicacion: string;
}

/**
 * `AFIRMADO` = alguien lo dijo y el cobro lo practica. `DEDUCIDO` = salió del
 * tipo de persona y el cobro NO lo practica hasta confirmarlo. La diferencia
 * es plata, así que se muestra.
 */
export type OrigenDelEjeDelEscenario = 'AFIRMADO' | 'DEDUCIDO' | 'SIN_DEFINIR';

export interface EjeDelEscenario {
  valor: boolean | null;
  origen: OrigenDelEjeDelEscenario;
  porque: string;
}

export interface EscenarioTributarioDelContrato {
  codigo: CodigoDeEscenario;
  nombre: string;
  /** El nombre literal del catálogo de Nuby, para poder cruzarlo. */
  nombreEnNuby: string | null;
  resumen: string;
  impuestos: ImpuestoDelEscenario[];
  sinImpuestos: boolean;
  certeza: 'CONFIRMADO' | 'DEDUCIDO' | 'SIN_DEFINIR';
  deducidos: string[];
  faltan: string[];
  ejes: {
    ivaSobreElCanon: EjeDelEscenario;
    retencionSobreElCanon: EjeDelEscenario;
    reteIvaSobreElCanon: EjeDelEscenario;
    retencionSobreLaComision: EjeDelEscenario;
  };
  fueraDelCatalogo: string[];
}

// ============================================================================
// Contract
// ============================================================================

/**
 * Full contract instance with signatures and terms
 */
export interface Contract {
  id: string;
  applicationId?: string;
  /**
   * `null` cuando el contrato es un MIGRADO al que la inmobiliaria decidió
   * no importarle el inmueble (T-0033). Es la fuente de verdad de "¿tiene
   * inmueble?" — clave todo render de "Sin inmueble" en esto, nunca en
   * `propertyAddress` vacío.
   */
  propertyId: string | null;
  /**
   * `null` en un contrato MIGRADO (T-0031) sin correo de inquilino — existe
   * como `Contract` igual, sin usuario inquilino asociado. No es un dato
   * ausente por error: es el estado real de una cartera migrada a medias.
   */
  tenantId: string | null;
  landlordId: string;
  /**
   * Número consecutivo del contrato (T-0040). Asignado por el servidor,
   * arranca en 1 por inmobiliaria — o por propietario cuando el contrato no
   * tiene inmobiliaria. Independiente del código de inmueble.
   *
   * Misma forma que `BackendProperty.code` y que el dominio `Property.code`:
   * un solo shape para un solo concepto en todo el front. Ausente sólo cuando
   * el `back` es anterior a T-0040; en ese caso **no se renderiza nada**
   * (nunca `—`, nunca `#0`). Guarda con `!= null`.
   */
  code?: number;
  /**
   * El número con el que la inmobiliaria conoce el contrato (su sistema
   * anterior), guardado al migrar. Es el que se lee grande en un contrato
   * migrado; `code` va al lado, nombrado como el de Leasefy. Ver
   * `lib/contratos/numero-del-contrato.ts`. `null` = no hay número;
   * `undefined` = el back no lo mandó.
   */
  externalId?: string | null;
  status: ContractStatus;

  // ── Terminación anticipada (back: migración 20260915170000) ──────────────
  //
  // 🔴 `status` NO distingue «lo terminaron antes de tiempo» de «se venció
  // solo»: los dos son `expired`, porque en el back `EXPIRED` ya significa
  // «terminado» y así están guardados los 1.145 contratos migrados como
  // «Terminado». Quien los distingue es `terminadoEn`.
  //
  // `undefined` = la migración todavía no está aplicada en esa base y el
  // back omite las columnas. Se lee igual que «no se terminó».
  /** `'2026-09-30'` — el día en que se terminó antes de tiempo. */
  terminadoEn?: string | null;
  /** El código del motivo (`MUTUO_ACUERDO`, `VENTA_DEL_INMUEBLE`, …). */
  motivoDeTerminacion?: string | null;
  notaDeTerminacion?: string | null;
  /** Hasta cuándo se había pactado, antes de que la terminación moviera `endDate`. */
  finPactadoOriginal?: string | null;

  // Snapshot fields (Opción A — capturados al crear el contrato, inmutables).
  // Pueden venir '' cuando el backfill no encontró el dato original.
  propertyAddress: string;
  propertyCity: string;
  tenantName: string;
  tenantEmail: string;
  tenantPhone: string;
  tenantDocument: string;
  landlordName: string;
  landlordEmail: string;
  landlordDocument: string;

  /**
   * `null` en un contrato MIGRADO sin ese dato (T-0031, D6 — nunca `0`/una
   * fecha inventada como sentinela de "desconocido"). Un renderizador que
   * recibe `null` acá DEBE mostrarlo como ausente — nunca formatear un
   * valor por default (`formatCurrency`/`formatDate` de `@/lib/format`
   * NO son null-safe en el sentido correcto para estos campos: resuelven a
   * "$ 0"/epoch, indistinguible de un dato real).
   */
  monthlyRent: number | null;
  adminFee: number;
  startDate: string | null;      // ISO date
  endDate: string | null;        // ISO date
  paymentDueDay: number | null;  // 1-28
  /**
   * Términos de cobro. `diasDePlazo: null` = hereda los de la inmobiliaria.
   * Opcionales en el tipo para no obligar a cada fixture viejo a declararlos;
   * el mapper (`mapBackendContract`) los llena SIEMPRE.
   */
  /**
   * 🔴 LA REFERENCIA DE RECAUDO: el número con el que este inquilino paga y
   * que el banco escribe en la línea del extracto. Es lo que deja que la
   * conciliación reconozca el pago en vez de adivinar por apellido.
   *
   * `null`/ausente = la inmobiliaria no cargó ninguna (o el back es anterior a
   * esta rama): se usa el consecutivo del contrato (`code`).
   */
  referenciaDeRecaudo?: string | null;
  prorratearPrimerMes?: boolean;
  diasDePlazo?: number | null;

  // ─── Administración ───────────────────────────────────────────────────────
  // No viajan en el documento firmado: corregirlos no invalida ninguna firma.
  // Se editan por PATCH /contracts/:id/administracion.
  //
  // Ver PerfilTributario / PerfilesDelContrato más abajo en este archivo.

  /** Decide el IVA del canon: vivienda excluida, comercial gravada. */
  usoInmueble?: 'VIVIENDA' | 'COMERCIAL' | null;
  periodicidad?: 'MENSUAL' | 'BIMESTRAL' | 'TRIMESTRAL' | 'SEMESTRAL' | 'ANUAL' | null;
  /** La del contrato — la que trajo el archivo migrado. */
  comisionPorcentaje?: number | null;
  /**
   * La de la consignación: **es la que liquida**. La dispersión y el extracto
   * leen ésta para pagarle al propietario. Viaja aparte para poder mostrar el
   * desacuerdo cuando las dos no coinciden, en vez de elegir un número.
   */
  comisionDeConsignacion?: number | null;
  /**
   * El propietario de verdad: la ficha de la consignación del inmueble.
   * `landlordName` en un contrato de inmobiliaria es el usuario que lo creó
   * o migró — no el dueño. `null` = sin inmueble o sin consignación;
   * `undefined` = el back no lo mandó (lista, respuesta vieja).
   */
  propietarioDeLaConsignacion?: {
    id: string;
    name: string;
    documentNumber: string;
  } | null;

  /**
   * TODOS los dueños del inmueble, con su porcentaje y su parte del canon.
   * Con un solo dueño es una lista de uno al 100 %; `undefined` = el back no
   * lo mandó (lista, respuesta vieja) y la ficha cae a
   * `propietarioDeLaConsignacion`.
   */
  propietariosDelContrato?: PropietariosDelContrato | null;
  /** Todos los inquilinos, el principal primero y marcado. */
  inquilinosDelContrato?: InquilinoDelContrato[] | null;

  /**
   * Quién retiene qué. La retención la practica **quien paga**, así que sin
   * esto la liquidación de cada concepto era una suposición.
   *
   * Cada perfil trae `esPorDefecto`: si la parte no tiene el dato configurado
   * se deduce del tipo de persona y se marca. Un supuesto y un hecho son cinco
   * booleanos idénticos — si no se distinguen, la pantalla muestra una
   * retención inventada con la misma cara que una real.
   */
  perfilesTributarios?: PerfilesDelContrato | null;
  /** El régimen ya resuelto por el back, con el origen de cada valor. */
  regimenTributario?: RegimenTributarioDelContrato | null;
  /**
   * Cómo se llama el escenario que forman las dos partes, y qué genera.
   * Opcional porque no todos los cables del contrato lo traen (la lista, por
   * ejemplo, sólo lo traería a costa de una consulta por fila).
   */
  escenarioTributario?: EscenarioTributarioDelContrato | null;
  /** null = heredar de la ficha del propietario. */
  arrendadorResponsableIva?: boolean | null;

  /**
   * Lo guardado tal cual, para poblar el formulario. `perfilesTributarios` ya
   * trae los defaults mezclados y no distingue «configurado como NATURAL» de
   * «vacío, y NATURAL es el default» — abrir el editor con eso convertiría un
   * vacío en una respuesta al guardar.
   */
  inquilinoTipoPersona?: 'NATURAL' | 'JURIDICA' | null;
  inquilinoResponsableIva?: boolean | null;
  inquilinoRetenedorRenta?: boolean | null;
  inquilinoRetenedorIva?: boolean | null;
  inquilinoRetenedorIca?: boolean | null;

  // Signatures
  landlordSignature: Signature | null;
  tenantSignature: Signature | null;

  // Uploaded PDF flow. `MIGRATED` = entró por la migración (casi siempre sin PDF).
  contractOrigin?: 'GENERATED' | 'UPLOADED_PDF' | 'MIGRATED';
  uploadedPdfPath?: string;
  insuranceTier?: 'NONE' | 'BASIC' | 'PREMIUM';
  customClauses?: Array<{ title: string; content: string }>;

  // Metadata
  createdAt: string;
  updatedAt: string;
  /** Fecha cuando el contrato quedó SIGNED (ambas partes firmaron). */
  signedAt?: string | null;
  /** Fecha cuando el contrato pasó a ACTIVE. */
  activatedAt?: string | null;

  // ─── Legacy / deprecated — mantenidos como opcionales hasta migrar consumers ─
  /** @deprecated backend no modela templates. Usar `contractOrigin` para inferir el tipo. */
  templateId?: string;
  /** @deprecated backend no modela type. Usar `contractOrigin` para el label. */
  type?: ContractType;
  /** @deprecated backend no modela garantías. */
  guaranteeType?: 'poliza' | 'codeudor';
  /** @deprecated backend no modela garantías. */
  guaranteeDetails?: string;
  /** @deprecated backend no modela cláusulas no negociables. */
  nonNegotiableClauses?: ContractClause[];
  /** @deprecated backend no modela condiciones especiales. */
  specialConditions?: string;

  // Hash SHA-256 del PDF final — disponible cuando el contrato está SIGNED.
  documentHash?: string;

  /**
   * @deprecated el backend no devuelve el timeline como array. Ver `AuditTrail` component,
   * que ahora deriva el timeline de los campos del contrato (createdAt + signatures + signedAt + activatedAt).
   */
  auditTrail?: ContractAuditEvent[];
}

// ============================================================================
// Contract Timeline Step
// ============================================================================

/**
 * Step in the contract signing timeline
 */
export interface ContractStep {
  id: string;
  title: string;
  description: string;
  status: 'completed' | 'current' | 'pending';
  completedAt?: string;
}

// ============================================================================
// Helper Types
// ============================================================================

/**
 * Data needed to create a new contract
 */
export interface CreateContractInput {
  propertyId: string;
  tenantId: string;
  templateId: string;
  monthlyRent: number;
  adminFee: number;
  startDate: string;
  endDate: string;
  paymentDueDay: number;
  guaranteeType: 'poliza' | 'codeudor';
  guaranteeDetails?: string;
  specialConditions?: string;
}

/**
 * Contract summary for list views
 */
export interface ContractSummary {
  id: string;
  propertyAddress: string;
  tenantName: string;
  status: ContractStatus;
  monthlyRent: number;
  startDate: string;
  endDate: string;
}
