/**
 * Contract types and interfaces
 * Types for rental contracts, signatures, and signing flow
 */

// ============================================================================
// Contract Type Enums
// ============================================================================

/**
 * Types of rental contracts
 */
export type ContractType = 'basico' | 'amoblado' | 'compartido' | 'custom';

/**
 * Contract status throughout the signing flow
 */
export type ContractStatus =
  | 'draft'                            // Borrador - being configured
  | 'pending_landlord'                 // Pendiente firma arrendador
  | 'pending_tenant'                   // Pendiente firma arrendatario
  | 'rejected_pending_modifications'   // Inquilino pidió cambios; landlord debe editar + re-firmar
  | 'signed'                           // Ambos firmaron, pendiente activar
  | 'active'                           // Activo - both signed
  | 'expired'                          // Expirado - past end date
  | 'cancelled';                       // Cancelado - terminated early

/**
 * Tipo de rechazo cuando un tenant rechaza un contrato en PENDING_TENANT_SIGNATURE.
 * - DEFINITIVE: cierra el proceso, contrato → CANCELLED, application → CONTRACT_FAILED.
 * - MODIFICATIONS: pide cambios, contrato → REJECTED_PENDING_MODIFICATIONS, landlord debe editar.
 */
export type RejectionType = 'DEFINITIVE' | 'MODIFICATIONS';

/**
 * Registro histórico de un rechazo. Una misma ronda de negociación puede tener varios.
 */
export interface ContractRejection {
  id: string;
  contractId: string;
  rejectedByUserId: string;
  type: RejectionType;
  reason: string;
  createdAt: string;
  rejectedBy: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
}

/**
 * Signature status for each party
 */
export type SignatureStatus = 'pending' | 'signed';

// ============================================================================
// Spanish Labels
// ============================================================================

/**
 * Spanish labels for contract types
 */
export const CONTRACT_TYPE_LABELS: Record<ContractType, string> = {
  basico: 'Contrato Basico',
  amoblado: 'Contrato Amoblado',
  compartido: 'Contrato Compartido',
  custom: 'Contrato Propio',
};

/**
 * Label legible para el "tipo de contrato" del lado del usuario. Como el backend no modela
 * `type` en el contract, derivamos el label del `contractOrigin`.
 */
export function getContractTypeLabel(
  contract: Pick<Contract, 'contractOrigin'>,
  locale: 'es' | 'en' = 'es',
): string {
  if (contract.contractOrigin === 'UPLOADED_PDF') {
    return locale === 'es'
      ? 'Contrato subido por el propietario'
      : 'Contract uploaded by landlord';
  }
  if (contract.contractOrigin === 'GENERATED') {
    return locale === 'es'
      ? 'Contrato generado por la plataforma'
      : 'Contract generated by the platform';
  }
  return locale === 'es' ? 'Contrato de arrendamiento' : 'Rental contract';
}

/**
 * Spanish descriptions for contract types
 */
export const CONTRACT_TYPE_DESCRIPTIONS: Record<ContractType, string> = {
  basico: 'Arriendo estandar sin muebles. Ideal para inquilinos que tienen sus propios muebles.',
  amoblado: 'Arriendo con muebles incluidos. Incluye inventario detallado de bienes.',
  compartido: 'Arriendo de habitacion con areas comunes compartidas.',
  custom: 'Sube tu propio contrato en formato PDF. Se usara como base para el proceso de firma.',
};

/**
 * Spanish labels for contract status
 */
export const CONTRACT_STATUS_LABELS: Record<ContractStatus, string> = {
  draft: 'Borrador',
  pending_landlord: 'Pendiente firma arrendador',
  pending_tenant: 'Pendiente firma arrendatario',
  rejected_pending_modifications: 'Modificaciones solicitadas',
  signed: 'Firmado — pendiente activar',
  active: 'Activo',
  expired: 'Expirado',
  cancelled: 'Cancelado',
};

/**
 * Status badge colors for contract status
 */
export const CONTRACT_STATUS_COLORS: Record<ContractStatus, string> = {
  draft: 'bg-muted text-foreground',
  pending_landlord: 'bg-plan-status-yellow-bg text-plan-status-yellow',
  pending_tenant: 'bg-plan-status-blue-bg text-plan-status-blue',
  rejected_pending_modifications: 'bg-[#F8F0E0] text-[#B7791F] dark:bg-[#B7791F]/15 dark:text-[#D2992F]',
  signed: 'bg-plan-status-blue-bg text-plan-status-blue',
  active: 'bg-plan-status-green-bg text-plan-status-green',
  expired: 'bg-muted text-muted-foreground',
  cancelled: 'bg-plan-status-red-bg text-plan-status-red',
};

// ============================================================================
// Contract Clause
// ============================================================================

/**
 * Individual clause within a contract template
 */
export interface ContractClause {
  id: string;
  title: string;
  content: string;
  required: boolean;
}

// ============================================================================
// Contract Template
// ============================================================================

/**
 * Reusable contract template with clauses
 */
export interface ContractTemplate {
  id: string;
  type: ContractType;
  name: string;
  description: string;
  clauses: ContractClause[];
}

// ============================================================================
// Signature
// ============================================================================

/**
 * Electronic signature with legal compliance metadata
 */
export interface Signature {
  signedAt: string;      // ISO date string
  signedBy: string;      // Name of signer
  signerId: string;      // User ID
  ipAddress: string;     // IP for legal record
  userAgent: string;     // Browser info for legal record
  status: SignatureStatus;
  otpVerified: boolean;       // Whether OTP verification was completed
  otpVerifiedAt?: string;     // ISO date string when OTP was verified
}

// ============================================================================
// Audit Trail
// ============================================================================

/**
 * Types of audit events in contract lifecycle
 */
export type ContractAuditEventType =
  | 'created'
  | 'sent_to_landlord'
  | 'landlord_signed'
  | 'sent_to_tenant'
  | 'tenant_signed'
  | 'activated';

/**
 * Audit event metadata
 */
export interface ContractAuditEventMetadata {
  userId?: string;
  userName?: string;
  ipAddress?: string;
  userAgent?: string;
  otpVerified?: boolean;
}

/**
 * Individual audit event in contract history
 */
export interface ContractAuditEvent {
  id: string;
  contractId: string;
  type: ContractAuditEventType;
  timestamp: string;        // ISO date string
  metadata: ContractAuditEventMetadata;
}

// ============================================================================
// Perfil tributario
// ============================================================================

/**
 * Si una parte es agente retenedor, y de qué.
 *
 * La retención en la fuente la practica **quien paga**: entre dos personas
 * naturales no hay; si el que paga es una empresa, sí. No depende de quién
 * recibe.
 */
export interface PerfilTributario {
  tipoPersona: 'NATURAL' | 'JURIDICA';
  /** Cobra IVA en sus facturas. */
  responsableIva: boolean;
  agenteRetenedorRenta: boolean;
  agenteRetenedorIva: boolean;
  agenteRetenedorIca: boolean;
  /**
   * Si algún campo se dedujo del tipo de persona en vez de leerse. Se muestra
   * en pantalla: un número calculado sobre un supuesto no se puede defender.
   */
  esPorDefecto: boolean;
}

export interface PerfilesDelContrato {
  inquilino: PerfilTributario;
  propietario: PerfilTributario;
  inmobiliaria: PerfilTributario;
}

// ============================================================================
// Contract
// ============================================================================

/**
 * Full contract instance with signatures and terms
 */
export interface Contract {
  id: string;
  applicationId?: string;
  /**
   * `null` cuando el contrato es un MIGRADO al que la inmobiliaria decidió
   * no importarle el inmueble (T-0033). Es la fuente de verdad de "¿tiene
   * inmueble?" — clave todo render de "Sin inmueble" en esto, nunca en
   * `propertyAddress` vacío.
   */
  propertyId: string | null;
  /**
   * `null` en un contrato MIGRADO (T-0031) sin correo de inquilino — existe
   * como `Contract` igual, sin usuario inquilino asociado. No es un dato
   * ausente por error: es el estado real de una cartera migrada a medias.
   */
  tenantId: string | null;
  landlordId: string;
  status: ContractStatus;

  // Snapshot fields (Opción A — capturados al crear el contrato, inmutables).
  // Pueden venir '' cuando el backfill no encontró el dato original.
  propertyAddress: string;
  propertyCity: string;
  tenantName: string;
  tenantEmail: string;
  tenantPhone: string;
  tenantDocument: string;
  landlordName: string;
  landlordEmail: string;
  landlordDocument: string;

  /**
   * `null` en un contrato MIGRADO sin ese dato (T-0031, D6 — nunca `0`/una
   * fecha inventada como sentinela de "desconocido"). Un renderizador que
   * recibe `null` acá DEBE mostrarlo como ausente — nunca formatear un
   * valor por default (`formatCurrency`/`formatDate` de `@/lib/format`
   * NO son null-safe en el sentido correcto para estos campos: resuelven a
   * "$ 0"/epoch, indistinguible de un dato real).
   */
  monthlyRent: number | null;
  adminFee: number;
  startDate: string | null;      // ISO date
  endDate: string | null;        // ISO date
  paymentDueDay: number | null;  // 1-28

  // ─── Administración ───────────────────────────────────────────────────────
  // No viajan en el documento firmado: corregirlos no invalida ninguna firma.
  // Se editan por PATCH /contracts/:id/administracion.
  //
  // Ver PerfilTributario / PerfilesDelContrato más abajo en este archivo.

  /** Decide el IVA del canon: vivienda excluida, comercial gravada. */
  usoInmueble?: 'VIVIENDA' | 'COMERCIAL' | null;
  periodicidad?: 'MENSUAL' | 'BIMESTRAL' | 'TRIMESTRAL' | 'SEMESTRAL' | 'ANUAL' | null;
  /** La del contrato — la que trajo el archivo migrado. */
  comisionPorcentaje?: number | null;
  /**
   * La de la consignación: **es la que liquida**. La dispersión y el extracto
   * leen ésta para pagarle al propietario. Viaja aparte para poder mostrar el
   * desacuerdo cuando las dos no coinciden, en vez de elegir un número.
   */
  comisionDeConsignacion?: number | null;

  /**
   * Quién retiene qué. La retención la practica **quien paga**, así que sin
   * esto la liquidación de cada concepto era una suposición.
   *
   * Cada perfil trae `esPorDefecto`: si la parte no tiene el dato configurado
   * se deduce del tipo de persona y se marca. Un supuesto y un hecho son cinco
   * booleanos idénticos — si no se distinguen, la pantalla muestra una
   * retención inventada con la misma cara que una real.
   */
  perfilesTributarios?: PerfilesDelContrato | null;

  /**
   * Lo guardado tal cual, para poblar el formulario. `perfilesTributarios` ya
   * trae los defaults mezclados y no distingue «configurado como NATURAL» de
   * «vacío, y NATURAL es el default» — abrir el editor con eso convertiría un
   * vacío en una respuesta al guardar.
   */
  inquilinoTipoPersona?: 'NATURAL' | 'JURIDICA' | null;
  inquilinoResponsableIva?: boolean | null;
  inquilinoRetenedorRenta?: boolean | null;
  inquilinoRetenedorIva?: boolean | null;
  inquilinoRetenedorIca?: boolean | null;

  // Signatures
  landlordSignature: Signature | null;
  tenantSignature: Signature | null;

  // Uploaded PDF flow
  contractOrigin?: 'GENERATED' | 'UPLOADED_PDF';
  uploadedPdfPath?: string;
  insuranceTier?: 'NONE' | 'BASIC' | 'PREMIUM';
  customClauses?: Array<{ title: string; content: string }>;

  // Metadata
  createdAt: string;
  updatedAt: string;
  /** Fecha cuando el contrato quedó SIGNED (ambas partes firmaron). */
  signedAt?: string | null;
  /** Fecha cuando el contrato pasó a ACTIVE. */
  activatedAt?: string | null;

  // ─── Legacy / deprecated — mantenidos como opcionales hasta migrar consumers ─
  /** @deprecated backend no modela templates. Usar `contractOrigin` para inferir el tipo. */
  templateId?: string;
  /** @deprecated backend no modela type. Usar `contractOrigin` para el label. */
  type?: ContractType;
  /** @deprecated backend no modela garantías. */
  guaranteeType?: 'poliza' | 'codeudor';
  /** @deprecated backend no modela garantías. */
  guaranteeDetails?: string;
  /** @deprecated backend no modela cláusulas no negociables. */
  nonNegotiableClauses?: ContractClause[];
  /** @deprecated backend no modela condiciones especiales. */
  specialConditions?: string;

  // Hash SHA-256 del PDF final — disponible cuando el contrato está SIGNED.
  documentHash?: string;

  /**
   * @deprecated el backend no devuelve el timeline como array. Ver `AuditTrail` component,
   * que ahora deriva el timeline de los campos del contrato (createdAt + signatures + signedAt + activatedAt).
   */
  auditTrail?: ContractAuditEvent[];
}

// ============================================================================
// Contract Timeline Step
// ============================================================================

/**
 * Step in the contract signing timeline
 */
export interface ContractStep {
  id: string;
  title: string;
  description: string;
  status: 'completed' | 'current' | 'pending';
  completedAt?: string;
}

// ============================================================================
// Helper Types
// ============================================================================

/**
 * Data needed to create a new contract
 */
export interface CreateContractInput {
  propertyId: string;
  tenantId: string;
  templateId: string;
  monthlyRent: number;
  adminFee: number;
  startDate: string;
  endDate: string;
  paymentDueDay: number;
  guaranteeType: 'poliza' | 'codeudor';
  guaranteeDetails?: string;
  specialConditions?: string;
}

/**
 * Contract summary for list views
 */
export interface ContractSummary {
  id: string;
  propertyAddress: string;
  tenantName: string;
  status: ContractStatus;
  monthlyRent: number;
  startDate: string;
  endDate: string;
}
